/** Canonical Samsung Galaxy phone parent models to keep in the catalog. */
export const SAMSUNG_PHONE_WHITELIST = [
  "Samsung Galaxy S25",
  "Samsung Galaxy S25+",
  "Samsung Galaxy S25 Ultra",
  "Samsung Galaxy S25 Edge",
  "Samsung Galaxy S25 FE",
  "Samsung Galaxy S26",
  "Samsung Galaxy S26+",
  "Samsung Galaxy S26 Ultra",
  "Samsung Galaxy A06",
  "Samsung Galaxy A06 5G",
  "Samsung Galaxy A07",
  "Samsung Galaxy A07 5G",
  "Samsung Galaxy A16",
  "Samsung Galaxy A17",
  "Samsung Galaxy A17 5G",
  "Samsung Galaxy A26",
  "Samsung Galaxy A26 5G",
  "Samsung Galaxy A27",
  "Samsung Galaxy A27 5G",
  "Samsung Galaxy A36",
  "Samsung Galaxy A36 5G",
  "Samsung Galaxy A37",
  "Samsung Galaxy A37 5G",
  "Samsung Galaxy A56",
  "Samsung Galaxy A56 5G",
  "Samsung Galaxy A57",
  "Samsung Galaxy A57 5G",
  "Samsung Galaxy Z Fold7",
  "Samsung Galaxy Z Flip7",
  "Samsung Galaxy Z Flip7 FE",
  "Samsung Galaxy Z TriFold",
] as const;

/** Reject even when source returns these models or categories. */
export const SAMSUNG_HARD_REJECT_PATTERNS = [
  /\bgalaxy\s+s24\s*\+?\b/i,
  /\bgalaxy\s+s24\s+ultra\b/i,
  /\bgalaxy\s+s24\s+fe\b/i,
  /\bgalaxy\s+s23\b/i,
  /\bgalaxy\s+s22\b/i,
  /\bgalaxy\s+a55\b/i,
  /\bgalaxy\s+a35\b/i,
  /\bgalaxy\s+a25\b/i,
  /\bgalaxy\s+a16\s+5g\b/i,
  /\bgalaxy\s+a15\b/i,
  /\bgalaxy\s+z\s+fold\s*6\b/i,
  /\bgalaxy\s+z\s+flip\s*6\b/i,
  /\bgalaxy\s+z\s+fold\s*5\b/i,
  /\bgalaxy\s+z\s+flip\s*5\b/i,
  /\bgalaxy\s+tab\b/i,
  /\bgalaxy\s+watch\b/i,
  /\bgalaxy\s+buds\b/i,
] as const;

export const SAMSUNG_ACCESSORY_PATTERNS = [
  /\bcase\s+for\b/i,
  /\bcover\s+for\b/i,
  /\bfor\s+(?:samsung\s+)?galaxy\b/i,
  /\bscreen\s+protector\b/i,
  /\btempered\s+glass\b/i,
  /\bprotector\s+glass\b/i,
  /\blens\s+protector\b/i,
  /\bcharger\b/i,
  /\bcable\b/i,
  /\badapter\b/i,
  /\bbumper\b/i,
  /\bfolio\b/i,
  /\bpouch\b/i,
  /\bstrap\b/i,
  /\bband\b/i,
  /\bwallet\b/i,
  /\bback\s+cover\b/i,
  /\bphone\s+case\b/i,
  /\bsmart\s+cover\b/i,
  /\bbook\s+cover\b/i,
] as const;

/** Parent models that must never merge with each other. */
export const SAMSUNG_NON_MERGE_GROUPS = [
  ["Samsung Galaxy S25", "Samsung Galaxy S25+", "Samsung Galaxy S25 Ultra", "Samsung Galaxy S25 Edge", "Samsung Galaxy S25 FE"],
  ["Samsung Galaxy S26", "Samsung Galaxy S26+", "Samsung Galaxy S26 Ultra"],
  ["Samsung Galaxy A06", "Samsung Galaxy A06 5G"],
  ["Samsung Galaxy A16", "Samsung Galaxy A16 5G"],
  ["Samsung Galaxy A17", "Samsung Galaxy A17 5G"],
  ["Samsung Galaxy A07", "Samsung Galaxy A07 5G"],
  ["Samsung Galaxy A26", "Samsung Galaxy A26 5G"],
  ["Samsung Galaxy A27", "Samsung Galaxy A27 5G"],
  ["Samsung Galaxy A36", "Samsung Galaxy A36 5G"],
  ["Samsung Galaxy A37", "Samsung Galaxy A37 5G"],
  ["Samsung Galaxy A56", "Samsung Galaxy A56 5G"],
  ["Samsung Galaxy A57", "Samsung Galaxy A57 5G"],
  ["Samsung Galaxy Z Fold7", "Samsung Galaxy Z Flip7", "Samsung Galaxy Z Flip7 FE", "Samsung Galaxy Z TriFold"],
] as const;
