/** Canonical Apple base product names to keep in the catalog. */
export const APPLE_PRODUCT_WHITELIST = [
  "iPhone 16e",
  "iPhone 17",
  "iPhone Air",
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",
  "iPhone 17e",
  "iPhone 18",
  "iPhone 18 Air",
  "iPhone 18 Pro",
  "iPhone 18 Pro Max",
  "MacBook Air 13-inch M4",
  "MacBook Air 15-inch M4",
  "MacBook Air 13-inch M5",
  "MacBook Air 15-inch M5",
  "MacBook Pro 14-inch M5",
  "MacBook Pro 14-inch M5 Pro",
  "MacBook Pro 14-inch M5 Max",
  "MacBook Pro 16-inch M5 Pro",
  "MacBook Pro 16-inch M5 Max",
  "Mac Studio 2025",
  "Mac mini M5",
  "Mac Studio M5",
  "MacBook Neo",
  "Studio Display 2026",
  "Studio Display XDR",
  "iPad 11th Gen (A16)",
  "iPad Air 11 M3",
  "iPad Air 13 M3",
  "iPad Air 11 M4",
  "iPad Air 13 M4",
  "iPad Pro 11 M5",
  "iPad Pro 13 M5",
  "iPad mini OLED",
  "iPad A18",
  "Apple Watch SE 3",
  "Apple Watch Series 11",
  "Apple Watch Ultra 3",
  "Apple Watch Series 12",
  "Apple Watch Ultra 4",
  "AirPods Pro 3",
  "AirPods Max 2",
  "AirPods Ultra",
  "Apple Vision Pro M5",
  "Apple TV 4K A17 Pro",
  "HomePod 3",
  "HomePod mini 2",
  "HomePad",
  "Apple Security Camera",
  "Apple Video Doorbell",
  "Magic Keyboard for iPad Air",
  "MagSafe Battery",
  "MagSafe Charger 25W Qi2",
  "AirTag 2",
] as const;
