/** Armenian MobileCentre spec labels → `product.specs.labels.*` i18n paths. */
export const PRODUCT_SPEC_ARMENIAN_LABEL_KEYS: ReadonlyArray<readonly [string, string]> = [
  ['Առկա է խանութներում', 'product.specs.labels.availableInStores'],
  ['Երաշխիք', 'product.specs.labels.warranty'],
  ['Հայտարարության տարին', 'product.specs.labels.announcementYear'],
  ['Օպերացիոն համակարգ', 'product.specs.labels.operatingSystem'],
  ['Էկրանի տեսակը', 'product.specs.labels.displayType'],
  ['Էկրանի տեսակ', 'product.specs.labels.displayType'],
  ['Էկրանի կետայնություն', 'product.specs.labels.screenResolution'],
  ['Էկրանի լուծաչափ', 'product.specs.labels.screenResolution'],
  ['Էկրանի չափսը', 'product.specs.labels.screenDiagonal'],
  ['Էկրանի անկյունագիծ', 'product.specs.labels.screenDiagonal'],
  ['Էկրանի չափս', 'product.specs.labels.screenDiagonal'],
  ['Դիմային տեսախցիկ', 'product.specs.labels.frontCamera'],
  ['Հիմնական տեսախցիկ', 'product.specs.labels.mainCamera'],
  ['Վեբ տեսախցիկ', 'product.specs.labels.webcam'],
  ['Ներկառուցված հիշողություն', 'product.specs.labels.builtInStorage'],
  ['Օպերատիվ հիշողություն', 'product.specs.labels.ram'],
  ['Կոշտ սկավառակի հիշողություն', 'product.specs.labels.builtInStorage'],
  ['Կոշտ սկավառակի տեսակ', 'product.specs.labels.storageType'],
  ['Գրաֆիկական հիշողություն', 'product.specs.labels.graphicsMemory'],
  ['Պրոցեսոր', 'product.specs.labels.processor'],
  ['Պրոցեսորի մոդել', 'product.specs.labels.processorModel'],
  ['SIM քարտի տեսակը', 'product.specs.labels.simCardType'],
  ['SIM քարտի տեսակ', 'product.specs.labels.simCardType'],
  ['Bluetooth', 'product.specs.labels.bluetooth'],
  ['Բլութուս', 'product.specs.labels.bluetooth'],
  ['Wi-fi', 'product.specs.labels.wifi'],
  ['Wi-Fi', 'product.specs.labels.wifi'],
  ['WiFi', 'product.specs.labels.wifi'],
  ['Ակումուլատոր', 'product.specs.labels.battery'],
  ['Մարտկոց', 'product.specs.labels.battery'],
  ['Արագ լիցքավորում', 'product.specs.labels.fastCharging'],
  ['Արագ գազարկում', 'product.specs.labels.fastCooling'],
  ['Ջրակայուն', 'product.specs.labels.waterResistant'],
  ['Չափսը', 'product.specs.labels.dimensions'],
  ['Չափսեր', 'product.specs.labels.dimensions'],
  ['Քաշը', 'product.specs.labels.weight'],
  ['Քաշ', 'product.specs.labels.weight'],
  ['Գույնը', 'product.specs.labels.color'],
  ['Գույն', 'product.specs.labels.color'],
  ['Մոդել', 'product.specs.labels.model'],
  ['Արտադրող', 'product.specs.labels.manufacturer'],
  ['Տեսակ', 'product.specs.labels.deviceType'],
  ['Սարքի տեսակ', 'product.specs.labels.deviceType'],
  ['Այլ', 'product.specs.labels.other'],
  ['Մարտկոցի Տեսակ', 'product.specs.labels.batteryType'],
  ['Մարտկոցի տեսակը', 'product.specs.labels.batteryType'],
  ['Մարտկոցի հզորությունը', 'product.specs.labels.batteryCapacity'],
  ['Մարտկոցի հզորություն', 'product.specs.labels.batteryCapacity'],
  ['ՕՀ տեսակ', 'product.specs.labels.operatingSystem'],
  ['Չիպ', 'product.specs.labels.processor'],
  ['Չիպ.', 'product.specs.labels.processor'],
  ['Չիպսեթ', 'product.specs.labels.processorModel'],
  ['Հիշողության քարտի բնիկ', 'product.specs.labels.simCardType'],
  ['Հիշողության քարտի բնիկը', 'product.specs.labels.simCardType'],
  ['Ստանդարտ Ցանց', 'product.specs.labels.network'],
  ['Ինտերնետի հասանելիություն', 'product.specs.labels.network'],
  ['WiFi Ցանց', 'product.specs.labels.wifi'],
  ['3G Ցանց', 'product.specs.labels.network'],
  ['4G LTE Ցանց', 'product.specs.labels.network'],
  ['4G LTE Ցանցի տիրույթ', 'product.specs.labels.network'],
  ['5G Ցանց', 'product.specs.labels.network'],
  ['Ձայն', 'product.specs.labels.other'],
  ['Բարձախոսներ', 'product.specs.labels.other'],
  ['Չափս', 'product.specs.labels.dimensions'],
  ['Լիցքավորման բնիկի տեսակը', 'product.specs.labels.connector'],
  ['Միացք', 'product.specs.labels.connector'],
  ['GPS', 'product.specs.labels.gps'],
  ['Gps', 'product.specs.labels.gps'],
  ['Լիցքավորում', 'product.specs.labels.charging'],
  ['Կշիռ', 'product.specs.labels.weight'],
  ['Հաստություն', 'product.specs.labels.dimensions'],
  ['Երկարություն', 'product.specs.labels.dimensions'],
  ['Լայնությունը', 'product.specs.labels.dimensions'],
  ['SIM քարտի քանակ', 'product.specs.labels.sim'],
  ['SIM', 'product.specs.labels.sim'],
  ['Աուդիո', 'product.specs.labels.other'],
  ['Տեսախցիկ', 'product.specs.labels.camera'],
  ['Կապ', 'product.specs.labels.network'],
];

/**
 * Group header titles from raw HTML / i18n sections.
 * Must not become spec row labels unless semantically recovered.
 * Excludes words that are also valid spec labels (e.g. "Processor" in English).
 */
export const PRODUCT_SPEC_SECTION_HEADER_TITLES = new Set<string>([
  'Հիմնական',
  'Ընդհանուր բնութագրեր',
  'Էկրան',
  'Հիշողություն',
  'Հիշողություն և Պրոցեսոր',
  'Պրոցեսորներ, Միջուկներ, Թելեր',
  'Տեսախցիկներ',
  'Կապ',
  'Ցանց',
  'Սնուցում',
  'Այլ',
  'General characteristics',
  'General',
  'Screen',
  'Display',
  'Memory',
  'Memory and processor',
  'Cameras',
  'Camera',
  'Network',
  'Connectivity',
  'Power',
  'Battery',
  'Physical',
  'Physical characteristics',
  'Основное',
  'Экран',
  'Дисплей',
  'Память',
  'Связь',
  'Батарея',
  'Физические характеристики',
  'Другое',
]);

/** @deprecated Use PRODUCT_SPEC_SECTION_HEADER_TITLES */
export const PRODUCT_SPEC_SECTION_ONLY_LABELS = PRODUCT_SPEC_SECTION_HEADER_TITLES;

/** English/Russian generic labels → i18n keys (value-aware refinement in semantic layer). */
export const PRODUCT_SPEC_GENERIC_LABEL_KEYS: ReadonlyArray<readonly [string, string]> = [
  ['Storage', 'product.specs.labels.builtInStorage'],
  ['Memory', 'product.specs.labels.ram'],
  ['Type', 'product.specs.labels.deviceType'],
  ['Other', 'product.specs.labels.other'],
  ['Device type', 'product.specs.labels.deviceType'],
  ['Operating system', 'product.specs.labels.operatingSystem'],
  ['Screen diagonal', 'product.specs.labels.screenDiagonal'],
  ['Screen resolution', 'product.specs.labels.screenResolution'],
  ['Display type', 'product.specs.labels.displayType'],
  ['RAM', 'product.specs.labels.ram'],
  ['Graphics memory', 'product.specs.labels.graphicsMemory'],
  ['Storage type', 'product.specs.labels.storageType'],
  ['Webcam', 'product.specs.labels.webcam'],
  ['Color', 'product.specs.labels.color'],
  ['Dimensions', 'product.specs.labels.dimensions'],
  ['Weight', 'product.specs.labels.weight'],
  ['Battery', 'product.specs.labels.battery'],
  ['Warranty', 'product.specs.labels.warranty'],
  ['Processor', 'product.specs.labels.processor'],
  ['Model', 'product.specs.labels.model'],
  ['Память', 'product.specs.labels.ram'],
  ['Встроенная память', 'product.specs.labels.builtInStorage'],
  ['Тип устройства', 'product.specs.labels.deviceType'],
  ['Тип накопителя', 'product.specs.labels.storageType'],
  ['Оперативная память', 'product.specs.labels.ram'],
  ['Операционная система', 'product.specs.labels.operatingSystem'],
  ['Диагональ экрана', 'product.specs.labels.screenDiagonal'],
  ['Разрешение экрана', 'product.specs.labels.screenResolution'],
  ['Тип экрана', 'product.specs.labels.displayType'],
  ['Графическая память', 'product.specs.labels.graphicsMemory'],
  ['Процессор', 'product.specs.labels.processor'],
  ['Модель процессора', 'product.specs.labels.processorModel'],
  ['Гарантия', 'product.specs.labels.warranty'],
  ['Модель', 'product.specs.labels.model'],
  ['Цвет', 'product.specs.labels.color'],
  ['Размеры', 'product.specs.labels.dimensions'],
  ['Вес', 'product.specs.labels.weight'],
  ['Веб-камера', 'product.specs.labels.webcam'],
  ['Фронтальная камера', 'product.specs.labels.frontCamera'],
  ['Основная камера', 'product.specs.labels.mainCamera'],
  ['Front camera', 'product.specs.labels.frontCamera'],
  ['Main camera', 'product.specs.labels.mainCamera'],
  ['Connector', 'product.specs.labels.connector'],
  ['GPS', 'product.specs.labels.gps'],
  ['Gps', 'product.specs.labels.gps'],
  ['SIM card', 'product.specs.labels.sim'],
  ['SIM Card', 'product.specs.labels.sim'],
  ['Sim card', 'product.specs.labels.sim'],
  ['SIM card type', 'product.specs.labels.simCardType'],
  ['Разъём', 'product.specs.labels.connector'],
  ['Разъем', 'product.specs.labels.connector'],
  ['SIM-карта', 'product.specs.labels.sim'],
  ['Тип SIM-карты', 'product.specs.labels.simCardType'],
];

export const PRODUCT_SPEC_ARMENIAN_LABEL_MAP = new Map<string, string>(
  PRODUCT_SPEC_ARMENIAN_LABEL_KEYS.map(([armenian, key]) => [armenian, key]),
);

export const PRODUCT_SPEC_GENERIC_LABEL_MAP = new Map<string, string>(
  PRODUCT_SPEC_GENERIC_LABEL_KEYS.map(([label, key]) => [label, key]),
);

/** Tokens that are status lines, not label/value pairs. */
export const PRODUCT_SPEC_STATUS_ONLY_ARMENIAN = new Set<string>(['Առկա է խանութներում']);

/** OS names that must not appear as standalone status above the specs table. */
export const PRODUCT_SPEC_OS_STATUS_VALUES = new Set<string>([
  'ios',
  'ipados',
  'android',
  'windows',
  'macos',
  'harmonyos',
  'linux',
]);

/** Default section slug for a spec label i18n key. */
export const PRODUCT_SPEC_LABEL_SECTION_SLUG: Readonly<Record<string, string>> = {
  'product.specs.labels.availableInStores': 'general',
  'product.specs.labels.warranty': 'warranty',
  'product.specs.labels.announcementYear': 'general',
  'product.specs.labels.operatingSystem': 'general',
  'product.specs.labels.deviceType': 'general',
  'product.specs.labels.model': 'general',
  'product.specs.labels.manufacturer': 'general',
  'product.specs.labels.displayType': 'screen',
  'product.specs.labels.screenResolution': 'screen',
  'product.specs.labels.screenDiagonal': 'screen',
  'product.specs.labels.frontCamera': 'cameras',
  'product.specs.labels.mainCamera': 'cameras',
  'product.specs.labels.webcam': 'connectivity',
  'product.specs.labels.builtInStorage': 'memory',
  'product.specs.labels.ram': 'memory',
  'product.specs.labels.storageType': 'memory',
  'product.specs.labels.graphicsMemory': 'memory',
  'product.specs.labels.processor': 'processor',
  'product.specs.labels.processorModel': 'processor',
  'product.specs.labels.simCardType': 'connectivity',
  'product.specs.labels.bluetooth': 'connectivity',
  'product.specs.labels.wifi': 'connectivity',
  'product.specs.labels.battery': 'power',
  'product.specs.labels.fastCharging': 'power',
  'product.specs.labels.fastCooling': 'power',
  'product.specs.labels.waterResistant': 'other',
  'product.specs.labels.dimensions': 'physical',
  'product.specs.labels.weight': 'physical',
  'product.specs.labels.color': 'general',
  'product.specs.labels.other': 'other',
  'product.specs.labels.batteryType': 'power',
  'product.specs.labels.batteryCapacity': 'power',
  'product.specs.labels.network': 'connectivity',
  'product.specs.labels.connector': 'connectivity',
  'product.specs.labels.charging': 'power',
  'product.specs.labels.sim': 'connectivity',
  'product.specs.labels.camera': 'cameras',
  'product.specs.labels.gps': 'connectivity',
};

export const PRODUCT_SPEC_SECTION_ORDER: readonly string[] = [
  'general',
  'screen',
  'memory',
  'processor',
  'cameras',
  'connectivity',
  'power',
  'physical',
  'warranty',
  'other',
];
